//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_LOGIN
    {
        public string COD_LOGIN { get; set; }
        public string COD_TIPO_LOG { get; set; }
        public string C_USER { get; set; }
        public string C_PASSWORD { get; set; }
    
        public virtual TIPO_LOGIN TIPO_LOGIN { get; set; }
    }
}
