//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CARWASHEntities : DbContext
    {
        public CARWASHEntities()
            : base("name=CARWASHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_AUTO> C_AUTO { get; set; }
        public virtual DbSet<C_LOGIN> C_LOGIN { get; set; }
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
        public virtual DbSet<COMPROBANTE_PAGO> COMPROBANTE_PAGO { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOes { get; set; }
        public virtual DbSet<MARCA_MATERIAL> MARCA_MATERIAL { get; set; }
        public virtual DbSet<MATERIALE> MATERIALES { get; set; }
        public virtual DbSet<ORDEN_ATENCION> ORDEN_ATENCION { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDORs { get; set; }
        public virtual DbSet<SERVICIO> SERVICIOs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TIPO_COMPROBANTE> TIPO_COMPROBANTE { get; set; }
        public virtual DbSet<TIPO_EMPLEADO> TIPO_EMPLEADO { get; set; }
        public virtual DbSet<TIPO_LOGIN> TIPO_LOGIN { get; set; }
        public virtual DbSet<TIPO_SERVICIO> TIPO_SERVICIO { get; set; }
        public virtual DbSet<VENTAS_DIARIAS> VENTAS_DIARIAS { get; set; }
        public virtual DbSet<DETALLE_ORDEN_ATENCION> DETALLE_ORDEN_ATENCION { get; set; }
        public virtual DbSet<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        public virtual DbSet<REGISTRAR_SERVICIO> REGISTRAR_SERVICIO { get; set; }
    }
}
