//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_AUTO
    {
        public int DNI { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CORREO { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public string PLACA { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public string CLASE { get; set; }
        public Nullable<int> NUM_ASI { get; set; }
    }
}
