//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPROBANTE_PAGO
    {
        public string COD_COMPROBANTE { get; set; }
        public string COD_ORDEN_ATENCION { get; set; }
        public string PLACA { get; set; }
        public string COD_TIPO_COMPRO { get; set; }
        public int DNI { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public string OBSERVACIONES { get; set; }
        public string IMPORTE_TOT { get; set; }
        public Nullable<double> SUBTOTAL { get; set; }
        public Nullable<double> IGV { get; set; }
    
        public virtual C_AUTO C_AUTO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ORDEN_ATENCION ORDEN_ATENCION { get; set; }
        public virtual TIPO_COMPROBANTE TIPO_COMPROBANTE { get; set; }
    }
}
