//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL_MARCA
    {
        public string COD_MATE { get; set; }
        public string COD_MARCA { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<double> PRECI_UNI { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public string DESCRIPCION1 { get; set; }
    }
}
