//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRAR_SERVICIO
    {
        public string COD_MATE { get; set; }
        public string COD_SERVICIO { get; set; }
        public int CANTIDAD { get; set; }
    
        public virtual MATERIALE MATERIALE { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
